### ISSUE TITLE
0.0.20 does not appear to migrate successfully (Django 1.9.4)

### ISSUE THREAD

**Issue by johndavidback** [yjmade/django-pgjsonb#10]
I installed 0.0.20 and it failed to migrate.  I downgraded to 0.0.16 and it worked okay.  Below is the stack trace.

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/core/management/**init**.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/raven/contrib/django/management/**init**.py", line 41, in new_execute
    return original_func(self, _args, *_kwargs)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(_args, *_options)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/Users/john/Git/casamatic-showings/env/lib/python3.4/site-packages/django_pgjsonb/fields.py", line 181, in add_field
    if field.db_index_options:
AttributeError: 'JSONField' object has no attribute 'db_index_options'

**Comment by johndavidback** [comment]
If I get a chance, I will try to help you debug it.

**Comment by yjmade** [comment]
fixed, thanks a lot, please `pip install -U django-pgjsonb` with the version 0.0.21
