### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '.../django_pgjsonb/VERSION'

### ISSUE THREAD

**Issue by furagu** [yjmade/django-pgjsonb#2]
Hi there!

Just tried to use the library and got this:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/furagu/projects/some-project/assets/models.py", line 3, in <module>
    from django_pgjsonb.fields import JSONField
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django_pgjsonb/__init__.py", line 5, in <module>
    VERSION = __version__ = pkg_resources.resource_string('django_pgjsonb', 'VERSION')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 966, in resource_string
    self, resource_name
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 1393, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 1514, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django_pgjsonb/VERSION'
```

**Comment by yjmade** [comment]
got it...I've fix this bug before and it show up again

**Comment by ghost** [comment]
have same error , no VERSION file in 0.0.10, from pypi

**Comment by CheckiO** [comment]
+1

**Comment by mastak** [comment]
+1

**Comment by dblenkus** [comment]
+1

**Comment by v0y** [comment]
+1

**Comment by yjmade** [comment]
do a pip install -U django-pgjsonb to fix the problem

**Comment by v0y** [comment]
@yjmade: :heart:
