### ISSUE TITLE
Makemigrations fails with 'No module named postgres.fields'

### ISSUE THREAD

**Issue by furagu** [yjmade/django-pgjsonb#3]
Hello again.

Tried to run `./manage.py makemigrations` and got this:

```
(some-project)MacBook-Pro-Egor:some-project furagu$ ./manage.py makemigrations 
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 90, in handle
    ProjectState.from_apps(apps),
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/db/migrations/state.py", line 108, in from_apps
    model_state = ModelState.from_model(model)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/db/migrations/state.py", line 178, in from_model
    field_class = import_string(path)
  File "/Users/furagu/Envs/some-project/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named postgres.fields
```

**Comment by mastak** [comment]
+1

**Comment by yjmade** [comment]
@mastak @furagu do a pip install -U django-pgjsonb to fix the problem
